services:
  # === Web Application ===
  spring:
    container_name: chat-service
    build: .
    ports:
      - "8443:8443"
    volumes:
      - ./ssl:/app/ssl
    depends_on:
      mysql:
        condition: service_healthy

  # === Database ===
  mysql:
    container_name: chat-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chat_service
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10