spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_service
    username: root
    password: 1234

  jpa:
    hibernate:
      # create: 애플리케이션 시작 시 기존 테이블을 모두 삭제하고 새로 생성. 데이터 초기화됨.
      # create-drop: create 처럼 테이블을 생성하고, 애플리케이션 종료 시 테이블도 삭제.
      # update: 엔티티 기준으로 DB 테이블을 자동 수정. 데이터는 유지됨.
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  # https 포트 번호: 8443
  # Tomcat, SSL
  port: 8443

  ssl:
    enabled: true
    key-store: classpath:ssl-server.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: spring

  servlet:
    session:
      cookie:
        same-site: None
        secure: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace