spring:
  application:
    name: chat-service

  thymeleaf:
    prefix: classpath:/templates/views
    suffix: .html
    cache: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/chat-service
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace