spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/chat-service
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    data:
      mongodb:
        uri: mongodb+srv://tjwnstjr27:sjs820@cluster.boyh9ls.mongodb.net/

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # 개발 중에는 캐시를 비활성화하는 것이 좋습니다.

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace