spring:
  application:
    name: chat-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # 개발 중에는 캐시를 비활성화하는 것이 좋습니다.

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/chat-service
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port:8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace